특정 닉네임을 가지는 사용자 프로필 조회
UMC-WithMe/WithMe_Back pull request #34
Opened 2023-01-18 13:21 UTC by sujeong11

close #25

## 작업 사항

- 입력받은 닉네임을 가진 Member 객체를 DB에서 찾아 MemberInfoGetResponse라는 DTO로 변환하여 반환하는 API 구현
  - 만약, 닉네임을 가지는 회원이 존재하지 않을 경우 NicknameNotFoundException 에러 발생
- 이번에는 에러 처리를 잘 한 것 같다. 에러 발생 시 잘 처리되는 것을 확인함.
- Member 객체에 값을 넣을 때 validation을 처리하므로 MemberInfoGetResponse에 별다른 validation 처리를 하지 않았는데 필요한가 싶다.

## 참고 자료

- 참고자료 (링크 등)

## 체크리스트

- [x]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [x]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [x]  팀의 코딩 컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [x]  내 코드에 대한 자기 검토가 되었는가?
- [x]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [x]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-01-18 16:31 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
[WithMe - Team convention 문서: DTO 관련 내용](https://www.notion.so/makeus-challenge/Ground-Rule-Convention-28fc2c757cb348e2bf6682fbf7b6578d#0c31533ca58440ea9e253d8bbb9147b4)
> **Response DTO(`XxxResponse`)**: API 응답 시 응답 데이터를 담기 위한 dto. API 별로 필요한 데이터가 다르므로 response dto는 여러 개가 될 수 있다. 이 dto는 다음과 같은 method들을 갖는다.
> - `of(..)`: 필요한 데이터들을 받아 dto를 생성하여 return하는 method. 필요한 경우에만 만들어도 된다.
> - `from(DTO)`: 일반 dto를 전달받아 response dto로 변환하여 return하는 method. 필요한 경우에만 만들어도 된다.

보시면 response dto는 일반 dto를 받아 본인을 생성하는 `from()` method를 갖는다고 작성해두었습니다. 사실 이렇게 하지 않아도 문제가 발생하는건 아닌데, 이렇게 정의해 둔 이유는 다음과 같습니다.
- 현재 코드의 경우 `MemberService.getMemberInfo(String nickname)`은 특정 API의 응답 데이터인 `MemberInfoGetResponse`를 응답한다. 
- 이렇게 되면 service layer의 특정 메서드가 controller layer의 특정 api에 종속되어 버린다. 그 때문에 추후 `MemberService.getMemberInfo(String nickname)`을 다른 api나 service layer의 다른 method에서 사용하기가 어려워진다.
- Service layer의 method가 controller layer의 특정 api에 연결되어 있지 않도록 구현한다면 추후 다른 method에서 다시 활용할 수 있으므로 재사용성과 유지보수성이 더 좋을 것이다.

그래서 DTO의 종류를 일반 dto, request dto, response dto로 나눈 것입니다. 일반 dto는 순전히 service <-> controller 계층 간의 데이터 전송을 위해서만 사용하고, request dto와 response dto는 일반 dto의 데이터를 사용하여 controller layer에서 필요한 로직을 처리합니다. 이렇게 하면 일반 dto를 반환하는 service layer의 method는 추후에 다른 service method나 controller method에서 재사용하기가 쉬워집니다. 즉, 확장 가능성과 유지보수를 염두에 둔 설계가 될 것이라고 생각합니다.
정리해보면 이렇습니다. 추후 다른 service layer의 method를 구현할 때도 동일하게 단일 값을 반환하는 상황이 아니라면 `MemberDto`를 controller layer로 반환합니다. 이러면 service layer는 `MemberDto`만 의존하면 됩니다. 반대로 controller layer에서는 `from()` method를 활용하여 일반 dto에서 필요한 값만을 사용하여 필요한 요청/응답 dto를 생성합니다.

이런 이유로 혹시 `Member` entity의 데이터들을 갖고 있는 `MemberDto`를 추가로 구현한 후, 다음과 같이 로직을 변경해보는 것은 어떨까요? 팀 내의 데이터 통신 로직을 통일하는게 추후 다른 사람의 코드를 이해하기 더 쉬워지므로 이왕 통일할거라면 이런 방식으로 하면 좋지 않을까 싶어서 조심스럽게 한 번 여쭤봅니다...! 😊
```suggestion
    public static MemberInfoGetResponse from(MemberDto dto) {
        return new MemberInfoGetResponse(dto.getNickname(), dto.getPhoneNumber(), dto.getBirth(), dto.getGender(), dto.getAddress());
    }
```

2023-01-18 16:39 UTC, hyeonnkang approved these changes

2023-01-19 01:00 UTC, dldmldlsy approved these changes

2023-01-19 02:55 UTC, sujeong11 commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
저는 이 방식으로 로직을 통일하는 것이 좋을 것 같습니다! 다른 팀원분들도 의견 남겨주시면 좋을 것 같네요😀

2023-01-19 04:21 UTC, hyeonnkang commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
저도 말씀하신 것처럼 DTO로 통일하는 방식이 좋을 것 같습니다!!

2023-01-19 05:43 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
조금 난해한 내용일 수 있었는데, 다들 의견 들어주셔서 감사합니다! 😊
@sujeong11 혹시 dto 아직 구현 안하셔서 코드 필요하시면 이거 쓰시면 될 것 같아요! 저 어차피 인증 기능 구현 때문에 만들어 뒀어요.
```java
package com.umc.withme.dto.member;

import com.umc.withme.domain.Address;
import com.umc.withme.domain.Member;
import com.umc.withme.domain.TotalPoint;
import com.umc.withme.domain.constant.Gender;
import com.umc.withme.domain.constant.RoleType;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.time.LocalDate;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public class MemberDto {

    private Long id;
    private Address address;
    private String email;
    private String phoneNumber;
    private String nickname;
    private LocalDate birth;
    private Gender gender;
    private TotalPoint totalPoint;
    private RoleType role;

    public static MemberDto of(Long id, Address address, String email, String phoneNumber, String nickname, LocalDate birth, Gender gender, TotalPoint totalPoint, RoleType role) {
        return new MemberDto(id, address, email, phoneNumber, nickname, birth, gender, totalPoint, role);
    }

    public static MemberDto from(Member member) {
        return MemberDto.of(
                member.getId(),
                member.getAddress(),
                member.getEmail(),
                member.getPhoneNumber(),
                member.getNickname(),
                member.getBirth(),
                member.getGender(),
                member.getTotalPoint(),
                member.getRole()
        );
    }

    public Member toEntity() {
        return Member.builder()
                .address(address)
                .email(email)
                .phoneNumber(phoneNumber)
                .birth(birth)
                .gender(gender)
                .build();
    }
}
```

2023-01-19 05:50 UTC, sujeong11 commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
넵, 감사합니다! 그런데 혹시 from 메서드 안에서 of로 Dto를 생성하는 이유가 따로 있을까요? 저는 from() 메서드로 바로 Dto를 생성하도록 작성하고 있었어서요

2023-01-19 05:55 UTC, Wo-ogie requested changes

2023-01-19 05:55 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
만약 `of()`가 없다면 `from()`에서 constructor를 사용하여 객체를 만드는게 맞구요, 근데 `of()`가 필요해서 만들어 둔 경우라면 이미 있는 factory method를 활용해서 객체를 생성하는 것이 좋아요.
왜냐하면 factory method에는 추후에 신규 객체를 생성하는데 필요한 추가 로직이 들어갈 수도 있는데, 일반적으로는 `from()` 등에서 객체를 생성할 때도 이 로직이 필요한 경우가 많거든요. 그래서 `of()`가 필요 없다면 안만들어도 되는데, 다른 곳에서 써야 해서 만들어 두었다면 만들어 둔 factory method를 활용하여 생성하는 것이 좋을 것 같습니다.

2023-01-19 05:55 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MemberService.java
>          return memeberRepository.existsByNickname(nickname);
헉 이거 지금 보니까 오타 있네요.
Repository layer class name `MemberRepository`로 수정해주세요!

2023-01-19 05:57 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
만약 `of()`가 없다면 `from()`에서 constructor를 사용하여 객체를 만드는게 맞구요, 근데 `of()`가 필요해서 만들어 둔 경우라면 이미 있는 factory method를 활용해서 객체를 생성하는 것이 좋아요.
왜냐하면 factory method에는 추후에 신규 객체를 생성하는데 필요한 추가 로직이 들어갈 수도 있는데, 일반적으로는 `from()` 등에서 객체를 생성할 때도 이 로직이 필요한 경우가 많거든요. 그래서 `of()`가 필요 없다면 안만들어도 되는데, 다른 곳에서 써야 해서 만들어 두었다면 만들어 둔 factory method를 활용하여 생성하는 것이 좋을 것 같습니다.

사실 나중에 필요할 때 수정해도 되는 부분이라 **그냥 `from()`에서 constructor로 객체 생성해서 return하셔도 됩니다**. 저는 그냥 저런 이유로 계속 이렇게 해왔어서, 그냥 스타일이에요 😅;

2023-01-19 05:59 UTC, sujeong11 commented on src/main/java/com/umc/withme/service/MemberService.java
>          return memeberRepository.existsByNickname(nickname);
넵 확인했습니다!

2023-01-19 06:02 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/member/NicknameNotFoundException.java
> +}
이거 저도 지금 만들고 있어서 고민중인데, 저는 일치하는 email이 없는 경우에 대한 custom exception이 필요한 상황이에요.
이거를 그때 그때 `NicknameNotFoundException`, `EmailNotFoundException`으로 만들어서 할지,
아니면 `MemberNotFoundException`으로 일관되게 처리할지 고민이 되는데 파크는 어떻게 생각해요?

2023-01-19 06:05 UTC, sujeong11 commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
> +    }
넵 답변 감사합니당😀

2023-01-19 06:07 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/member/NicknameNotFoundException.java
> +}
전자는 error message를 좀 더 세분화 할 수 있다는 장점이 있는 대신, exception이 그만큼 많아진다는 단점이 있고
후자는 하나로 처리를 하니 exception이 많아지지는 않지만 error message를 세분화하기 어렵다는 단점이 있다고.... 생각했는데
좀 더 생각해보니 `NotFoundException(String optionalMessage)`를 사용해서 추가적인 메시지를 전달하면 단점이 어느 정도 해결되네요?
그럼 후자가 괜찮을 것 같은데 어떨까요?

`MemberNotFoundException`을 다음과 같이 만들고
```java
public class MemberNotFoundException extends NotFoundException {
    
    public MemberNotFoundException(String optionalMessage) {
        super(optionalMessage);
    }
}
```

사용할 때 `.orElseThrow(() -> new MemberNotFoundException("nickname=" + nickname))` 이런식으로 하면 될 것 같은데

2023-01-19 06:17 UTC, sujeong11 commented on src/main/java/com/umc/withme/exception/member/NicknameNotFoundException.java
> +}
에러 처리할 것이 많으면 `NotFoundException(String optionalMessage)`를 사용하는 것이 좋을 것 같습니다. 그런데 현재 `NicknameNotFoundException, EmailNotFoundException` 2개만 처리하면 되니 조금 더 명확하게 보이도록 따로따로 구현하면 어떨까 싶습니다!

2023-01-19 06:18 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/member/NicknameNotFoundException.java
> +}
넵 그러면 저도 그렇게 구현할게요. 추후에 많아지면 그때 refactoring 하면 될 것 같습니당.

2023-01-19 06:49 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MemberService.java
> +        return MemberDto.from(findMember);
Comment가 많아서 좀 죄송하기도 한데,,, 마지막으로 하나만 더 달겠습니다. 하하 😅;;
`Optional`은 mapping을 지원하므로 다음과 같이 하면 변수 선언 없이 필요한 dto를 return 할 수 있어 코드가 조금 더 깔끔해질 것 같습니다!

```suggestion
    return memberRepository.findByNickname(nickname)
            .map(MemberDto::from)
            .orElseThrow(NicknameNotFoundException::new);
```

2023-01-19 06:57 UTC, sujeong11 commented on src/main/java/com/umc/withme/service/MemberService.java
> +        return MemberDto.from(findMember);
아닙니다! 제가 놓친 부분에 대해 피드백 주셔서 감사합니당😀 반영 후 푸쉬했습니당

2023-01-19 06:57 UTC, Wo-ogie approved these changes
수고하셨습니다! 👍

2023-01-19 06:59 UTC, merged