모임 생성 기능 구현
UMC-WithMe/WithMe_Back pull request #43
Opened 2023-01-20 13:26 UTC by hyeonnkang

## 작업 사항
close #17
- 모임 생성 기능 api 까지 구현 완료했습니다.
- 현재 MeetService의 createMeet 메소드 내부에서 동네 목록을 가져올 때 orElseThrow가 잘 되지 않아 현재 Optional 을 get으로 가져오는 방법을 사용했습니다. 피드백 주시면 수정할 수 있도록 하겠습니다!

## 참고 자료

- 참고자료 (링크 등)

## 체크리스트

- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-01-20 14:04 UTC, Wo-ogie requested changes

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
> +    public ResponseEntity<DataResponse> createMeet(@Validated @RequestBody MeetCreateRequest meetCreateRequest){
`@RequestBody`에 대한 검증이 필요하신거면 `@Valid`만으로도 충분할 것 같습니다. 그리고 이 경우 class level에 달려있는 `@Validated`는 필요 없을 것 같아요.

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetAddressDto.java
> +}
1. DTO의 내용이 `MeetAddressDto` 보다는 `AddressDto`가 적합할 것 같습니다. `MeetAddress`에 대한 내용을 담고 있는 dto가 아닌, `Address`에 대한 내용을 담고 있는 dto니까요. 쓰고 계신 곳이 `MeetAddress`와 관련한 곳이라서 이렇게 이름 지은 것 같은데, `AddressDto`가 딱 이 모양일 것 같네요? 사실 저도 지금 이거랑 똑같은 `AddressDto`를 만들어서 쓰고 있는데, `MeetAddressDto`보다는 `AddressDto`가 적합할 것 같습니다.
2. `Address` entity는 저희가 더 생성할 일이 없습니다. 따라서 `Address` entity를 생성하는 코드는 필요하지도 않고, 구현하면 안됩니다. 이러한 이유 때문에 `toEntity()`는 삭제 해주시는 것이 좋을 것 같습니다.
3. [이전 코드리뷰](https://github.com/UMC-WithMe/WithMe_Back/pull/34#discussion_r1080835952)에도 비슷한 내용이 있는데, 객체를 생성하는 `of()` method가 존재하는 상황이니 `from()`에서는 생성자 대신 `of()` 메서드를 활용해서 객체를 생성해보는 것은 어떨까요?

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Meet.java
> +        this.endDate = endDate;
모임 게시글 등록 시 시작일과 종료일은 받지 않는 걸로 알고 있는데... 아닐까요?
그래서 `startDate`, `endDate`를 nullable로 했고, 시작 일시와 종료 일시는 모임 인원 모집이 완료되면 그 때 입력받는 것으로 알고 있습니다.

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetCreateRequest.java
> +    private MeetStatus meetStatus;
`recruitStatus`는 entity 생성 시 `PROGRESS` 값으로 설정되도록 생성자가 구현되어 있고, 화면 설계서에도 모집 상태를 입력받고 있지는 않은 것 같습니다.
마찬가지로 `meetStatus`는 인원 모집 후 정해지는 값이라 처음에는 null이 저장될 것 입니다. 모임 생성 시 요청 데이터로 받을 필요가 없지 않을까요?

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetDto.java
> +    private MeetLeaderDto leader;  // 이 모임의 리더
[디코 코드리뷰]
`MemberDto`로 변경

2023-01-20 14:04 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetDto.java
> +    }
[디코 코드리뷰]
삭제해주세요

2023-01-20 14:31 UTC, Wo-ogie commented on src/test/java/com/umc/withme/service/MeetServiceTest.java
> +class MeetServiceTest {
[디코 코드리뷰]
`@Disabled("추후에 작성할 테스트임")`

2023-01-20 14:31 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetDto.java
> +        meetDto.setAddresses(addresses);
`this.addresses = addresses`

2023-01-20 17:19 UTC, Wo-ogie approved these changes
제가 보기에는 크게 문제 없어보이는데.... postman으로 테스트 꼼꼼히  해주시고, 문제 없으면 merge 하셔도 될 것 같습니다.
수고하셨어요! 👍

2023-01-21 03:30 UTC, sujeong11 approved these changes

2023-01-21 05:20 UTC, dldmldlsy approved these changes

2023-01-21 05:21 UTC, merged