Review와 Point 엔티티 생성
UMC-WithMe/WithMe_Back pull request #44
Opened 2023-01-20 16:19 UTC by sujeong11

close #39

## 작업 사항

- 작성해둔 erd를 바탕으로 Review와 Point 엔티티 생성
- 한 엔티티에서 같은 엔티티를 두개 이상 참조할 때 에러 발생했고, 아래와 같이 코드 수정하니 테이블이 잘 생성됨.
  - name 속성 값을 제거하면 되었다. @JoinColumn에는 name 속성으로 매핑할 외래키를 적어줘야 된다고 이해하고 있었지만 이것이 아니라 참조하는 엔티티가 하나일 때 식별하기 쉽게 적어주는 것이었다.
  - name 속성이 없으면 `"필드명_참조하는 외래키의 기본키 칼럼명"`로 연관관계 매핑
  - ex) `sender_id_member_id`

[전]
```java
@JoinColumn(name = "member_id", nullable = false)
@ManyToOne(fetch = FetchType.LAZY)
private Member sender_id;

@JoinColumn(name = "member_id", nullable = false)
@ManyToOne(fetch = FetchType.LAZY)
private Member receiver_id;
``` 
[후]
```java
@JoinColumn(nullable = false)
@ManyToOne(fetch = FetchType.LAZY)
private Member sender_id;

@JoinColumn(nullable = false)
@ManyToOne(fetch = FetchType.LAZY)
private Member receiver_id;
``` 

## 참고 자료

- 참고자료 (링크 등)

## 체크리스트

- [x]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [x]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [x]  팀의 코딩 컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [x]  내 코드에 대한 자기 검토가 되었는가?
- [x]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [x]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-01-20 17:25 UTC, Wo-ogie requested changes

2023-01-20 17:25 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Point.java
> +    private Integer contact_speed;
```suggestion
    @Column(nullable = false)
    private Integer contactSpeed;
```
이거 java 변수명이니까 camel-case로 작성해주세요!

2023-01-20 17:25 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Review.java
> +    private Member receiver_id;
```suggestion
    @JoinColumn(name = "sender_id", nullable = false)
    @ManyToOne(fetch = FetchType.LAZY)
    private Member sender;

    @JoinColumn(name = "receiver_id", nullable = false)
    @ManyToOne(fetch = FetchType.LAZY)
    private Member receiver;
```
이것도 camel-case로 작성해주세요. 그리고 변수명에 id는 필요 없을 듯 합니다.
위와 같이 설정하시면 괜찮지 않을까요?

2023-01-20 17:25 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Point.java
> +    }
Constructor의 access modifier를 `private`으로 해서 builder로만 entity를 생성할 수 있게 강제해주시면 좋을 것 같습니다.

2023-01-20 17:25 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Review.java
> +    }
이것도 constructor의 access modifier를 `private`으로 해서 builder로만 entity를 생성할 수 있게 강제해주시면 좋을 것 같습니다.

2023-01-20 17:29 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/Review.java
> +public class Review extends BaseTimeEntity {
일단 ERD 상으로는 `created_by`랑 `updated_by`도 들어가 있으니까요 `BaseEntity` 상속 받아주시면 좋을 것 같습니다.

2023-01-21 03:40 UTC, Wo-ogie approved these changes

2023-01-21 04:42 UTC, hyeonnkang approved these changes

2023-01-21 05:20 UTC, dldmldlsy approved these changes

2023-01-21 06:28 UTC, merged