모임 삭제 API 구현
UMC-WithMe/WithMe_Back pull request #53
Opened 2023-01-23 06:27 UTC by hyeonnkang

## 작업 사항
close #49
- 모임을 삭제 하는 API를 컨트롤러 Layer 까지 생성하고 postman으로 삭제 테스트 까지 진행했다.
- 
현재 mapping 메소드가 DELETE로 되어있는데 추가 테이블에 컬럼을 넣고 PATCH로 변경할 지는 추후 논의가 필요할 것 같다

## 참고 자료

- 참고자료 (링크 등)

## 체크리스트

- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-01-27 02:39 UTC, Wo-ogie commented
이거 일단 Conflict부터 해결해주세요~

2023-01-27 22:22 UTC, Wo-ogie requested changes

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
> +    })
`@ApiResponses`를 설정하지 않으면 기본적으로 200 success에 대한 부분은 swagger가 자동 생성해주기 때문에 별다른 작성하신 이유가 없다면 삭제해도 될 것 같습니다.

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetDeleteResponse.java
> +}
삭제 성공 시 삭제한 모임의 id(PK)를 응답하는 이유가 있을까요?

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/repository/MeetAddressRepository.java
> +import java.util.Optional;
불필요한 import문 같아 보이는데, 확인해보시고 필요 없는거면 삭제해주시면 좋을 것 같습니다.

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/repository/MeetMemberRepository.java
> +    List<MeetMember> findByMeet_Id(Long meetId);
`MeetAddressRepository`의 경우처럼 리스트 조회임을 method name에 명시해주시면 좋을 것 같아요.

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +                .orElseThrow(NicknameNotFoundException::new);
`memberName`은 `email` 또는 `memberEmail`로 값과 관련 있는 변수명으로 해주시는게 좋을 것 같고, repository에서 조회할 때는 `findByEmail`을 사용해야하지 않을까요?

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +                .orElseGet(null);
삭제하려는 모임이 없을 때 `meet`에 `null`을 넣는 이유가 있나요? 특별한 이유가 없다면 별로 좋지 않아보입니다.

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +                .orElseThrow(UnauthorizedException::new);
여기는 왜 `UnauthorizedException`을 던지는걸까요? 해당 예외와 관련 없어 보이는 상황같은데...

2023-01-27 22:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +    }
1. 다음과 같이 하시면 `if-else` 구문에서 `if`문으로 간략화 할 수 있으며, 조건문의 볼륨도 작아집니다.
```java
if (!meetLeader.equals(member)) {
    // throw new 관련 예외;
}
// 정상 로직 수행
```

2. 위에서 한 번 조회했던 모임이 있는데 굳이 또 조회해야 할까요?

3. 예외의 naming을 `DeleteBadRequestException`으로 하는 것이 좋을지 조금 고민이 되는 부분입니다. 정말 client에서 **요청을 잘못 한 것**이 맞을까요? 이 경우에는 요청 방법이 잘못되거나 한 경우라기 보다는 **특정 resource를 수정/삭제할 권한이 없는 상황**으로 보는 것이 더 적합할 것 같습니다. 또한 custom exception의 naming에 모임 관련된 예외임을 드러내주는 것이 좋을 것 같고, `ExceptionType`에 error message도 이러한 내용들이 잘 작성되었으면 좋겠습니다.

4. Custom exception을 정의하셨으면 `ExceptionType`에 관련 내용도 **반드시 작성해주세요**. 이 작업을 하지 않으면 추후 client에서는 어떤 상황이든지 "알 수 없는 에러가 발생했습니다"만 보게 되어 뭐 때문에 문제가 되는 상황인지 파악하기가 어려워집니다.

2023-01-28 04:36 UTC, hyeonnkang commented on src/main/java/com/umc/withme/dto/meet/MeetDeleteResponse.java
> +}
응답으로 필요한 데이터가 마땅히 생각나지 않아 DataResponse<>() 안에 아무것도 안넣으니 오류가 나더라구요. 
그래서 모임 id 그냥 반환하는 걸로 했는데 MeetDeleteResponse 클래스만 놔두고 meetId 는 삭제하는게 나으려나요?

2023-01-28 05:17 UTC, hyeonnkang commented on src/main/java/com/umc/withme/dto/meet/MeetDeleteResponse.java
> +}
meetId 필드를 삭제하니까 json으로 파싱할게 없어서인지 오류가 발생해서 이 부분은 그대로 놔두고 다른 피드백들은 모두 수정사항 반영해서 푸쉬했습니다!

2023-01-28 05:52 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetDeleteResponse.java
> +}
응답할 데이터가 없는 경우에는 메타데이터만 존재하는 `BaseResponse`를 응답하시면 됩니다.

2023-01-28 05:53 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
>                  .orElseThrow(NicknameNotFoundException::new);
이메일로 조회하는 상황이니까 예외도 적절하게 바꿔주세요

2023-01-28 06:09 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
>      @GetMapping("/meets/{meetId}")
API 명세는 프론트엔드 개발자분들이 보게 될 문서니까, 이 내용을 고려해서 조금 더 신경써주시면 좋을 것 같습니다.
현재 프론트엔드에서 API를 호출할 때 모임의 PK 값을 전달하는데 이 이름이 지금 `meetId`이므로 API 명세에도 `meetId`라고 명시해주는 게 더 명확할 것 같아요. `id`라고만 적어도 대충 알아는 듣겠지만, 좀 더 친절하게 작성해주면 더 좋겠죠?

2023-01-28 06:09 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/ExceptionType.java
> +    MEET_DELETE_UNAUTHORIZED_EXCEPTION(2100, "해당 모임을 삭제할 권한이 없습니다.", MeetIdNotFoundException.class),
여기 수정해주세요.

2023-01-28 06:09 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/meet/MeetDeleteUnauthorizedException.java
> +public class MeetDeleteUnauthorizedException extends UnauthorizedException {
이 예외의 경우 unauthorized 보다는 forbidden이 적합하지 않을까요?

2023-01-28 06:11 UTC, Wo-ogie commented
Controller class type level에 `@Tag` annotation 활용해서 제목도 간단하게 붙여주시면 좋을 것 같아요.

2023-01-28 06:25 UTC, hyeonnkang commented on src/main/java/com/umc/withme/exception/meet/MeetDeleteUnauthorizedException.java
> +public class MeetDeleteUnauthorizedException extends UnauthorizedException {
넵 말씀하신 부분 전부 고쳐서 푸쉬했습니다! 감사합니다!

2023-01-29 04:57 UTC, sujeong11 approved these changes

2023-01-29 05:54 UTC, Wo-ogie commented on src/main/java/com/umc/withme/exception/ExceptionType.java
> +    MEET_DELETE_FORBIDDEN_EXCEPTION(2300, "해당 모임을 삭제할 권한이 없습니다.", MeetDeleteForbiddenException.class),
Forbidden은 403에러니까 저희 회의 때 얘기한대로면 에러 코드가 2401이 될 것 같습니다.

2023-01-29 05:54 UTC, dldmldlsy approved these changes

2023-01-29 05:56 UTC, hyeonnkang commented on src/main/java/com/umc/withme/exception/ExceptionType.java
> +    MEET_DELETE_FORBIDDEN_EXCEPTION(2300, "해당 모임을 삭제할 권한이 없습니다.", MeetDeleteForbiddenException.class),
넵 변경했습니다!

2023-01-29 07:11 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +            throw new MeetDeleteForbiddenException(meet.getId(), memberEmail);
이거 비교를 다음과 같이 PK로 하면 `meetLeader`를 조회하는 코드가 없어도 될 것 같아요. 그럼 코드가 더 간결해질 것 같습니다. 어떨까요?
```java
if (meet.getCreatedBy().equals(member.getId()) {
    throw 예외;
}
```

심지어는 `deleteMeetById()`가 전달받는 argument가 `String memberEmail`이 아닌 `Long loginMemberId`라면 "모임을 삭제하려고 하는 사용자"조차 조회할 필요 없이 다음과 같이 검증이 가능할 것 같습니다.
```java
if (!loginMemberId.equals(meet.getCreatedBy())) {
    throw 예외
}
```
참고로 로그인한 사용자의 PK는 controller method에서 `principle.getMemberId()`로 받을 수 있습니다.

2023-01-29 08:25 UTC, hyeonnkang commented on src/main/java/com/umc/withme/service/MeetService.java
> +            throw new MeetDeleteForbiddenException(meet.getId(), memberEmail);
넵 말씀해주신 부분 확인하고 수정했습니다! 감사합니다!

2023-01-29 08:29 UTC, Wo-ogie approved these changes
조금 천천히 해도 괜찮으니, 다음에 작업하실 때도 꼼꼼히 코드리뷰 내용들 고려하시면서 하시면 더 좋을 것 같습니다. 😊
수고하셨습니다!

2023-01-29 08:31 UTC, merged