모임 단건 조회 기능 구현
UMC-WithMe/WithMe_Back pull request #63
Opened 2023-01-26 16:36 UTC by hyeonnkang

## 관련 이슈
- close #62 

## 작업 사항
- erd 커밋을 docs로 변경
- Meet Builder 에서 createdBy 및 updatedBy 설정 삭제
- Meet의 toString 삭제
- MeetController의 api url meets 로 변경
- MeetServiceTest 삭제 ( 이유 : Meet 생성 시 Member 넣어 주기 에서 오류가 발생해 이를 해결하지 못했습니다. swagger 테스트는 잘 작동하는 상태입니다.)

## 참고 자료
- 참고자료 (링크 등)

## 체크리스트
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-01-26 16:46 UTC, Wo-ogie commented
Issue 그냥 #45 reopen해서 하시면 되지 않을까요? 굳이 issue 따로 만들어서 안해도 될 것 같아요.

2023-01-26 17:03 UTC, Wo-ogie requested changes

2023-01-26 17:03 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
>      ) {
`MemberCreateResponse`, `MeetCreateRequest`에도 API 명세 작성해주세요. `MemberCreateResponse`와 `MeetCreateRequest` 안에 있는 DTO가 있다면 거기도 함께 작성해주시면 좋을 것 같습니다.
`@Schema`로 example 값이랑 description 작성할 수 있고, 제가 한 거 참고하시면 됩니다.

2023-01-26 17:03 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
> +    public ResponseEntity<DataResponse<MeetInfoGetResponse>> getMeet(@PathVariable Long meetId) {
여기도 `MeetInfoGetResponse`에 API 명세 작성해주세요. `MeetInfoGetResponse` 안에 있는 DTO가 있다면 거기도 함께 작성해주시면 좋을 것 같습니다.

2023-01-26 17:03 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetService.java
> +                .orElseThrow(UnauthorizedException::new);
로그인 사용자가 없는 경우에 대한 예외처리는 따로 하고 있으니, 그냥 `EmailNotFoundException`을 throw하셔도 될 것 같아요.

2023-01-26 17:24 UTC, Wo-ogie commented on src/main/java/com/umc/withme/controller/MeetController.java
> +    })
여기 `@Operation` description 부분에 오타 있어요.

그리고 `@ApiResponse`는 해당 api에 대해 명시해야 할 사항이 경우에만 작성해주시면 될 것 같습니다. 모든 예외 상황에 대해서 다 하려면 너무 코드가 길어질 것 같아서요. 그래서 404는 굳이 없어도 되지 않을까..? 싶어요. 어떻게 생각하실까요?
이렇게 말하고 제 코드를 보니 저도 굳이 작성 안했어도 됐을 것 같네요.

2023-01-27 01:18 UTC, hyeonnkang commented on src/main/java/com/umc/withme/controller/MeetController.java
> +    })
넵 위에 말씀하신 피드백 모두 반영해서 푸쉬했습니다! 감사합니다!

2023-01-27 02:19 UTC, Wo-ogie requested changes

2023-01-27 02:19 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetCreateRequest.java
>      private List<AddressRequest> addresses;
이거 이렇게 하지 말고 그냥 `AddressRequest`에 `@Schema`로 명세 작성해주시면 됩니다.

2023-01-27 02:19 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/member/MemberInfoGetResponse.java
>      private Integer ageRange;
이거 `Integer` 값이라서 `20`, `30` 이렇게 응답되지 않나요?

2023-01-27 02:19 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetInfoGetResponse.java
>      private List<AddressDto> addresses;  // 이 모임에 설정된 동네 리스트
여기도 `AddressDto`만 명세 작성해놓으면 그거 쓰도록 하는게 좋을 거 같아요.

2023-01-27 02:19 UTC, Wo-ogie commented on src/main/java/com/umc/withme/dto/meet/MeetInfoGetResponse.java
>      private MemberInfoGetResponse leader;  // 이 모임의 리더
`MemberInfoGetResponse` 명세가 표시되는 부분이라 `@Schema` 없어도 될 것 같습니다. 실제로 Swagger 돌려봐도 작성한 예시나 설명은 보이지 않네요.
굳이 이점이 있다면 코드 상에서 명시할 수 있다는 정도인데, 이 부분은 주석으로 사용하면 될 것 같습니다.
만약 `MemberInfoGetResponse` 전체에 대한 설명을 작성하고 싶으신거면 `MemberInfoGetResponse` class level에 `@Schema(description=)`을 붙이셔야 합니다.

2023-01-27 02:27 UTC, hyeonnkang commented on src/main/java/com/umc/withme/dto/meet/MeetInfoGetResponse.java
>      private MemberInfoGetResponse leader;  // 이 모임의 리더
넵 ageRange 변수명만 보고 example 작성했는데 Integer 값인거 확인하고 변경해놓았습니다. 나머지 부분들도 모두 수정해서 푸쉬했습니다!

2023-01-27 02:38 UTC, Wo-ogie approved these changes
수고하셨습니다! 모임 삭제 API PR 올리신 것도 여기에서 언급한 코멘트들에 해당 사항 없는지 한 번 확인해주시면 좋을 것 같아요.

2023-01-27 04:31 UTC, dldmldlsy approved these changes

2023-01-27 10:54 UTC, Wo-ogie commented
@sujeong11 혹시 시간 되시면 리뷰 부탁드립니다!

2023-01-27 11:42 UTC, sujeong11 approved these changes

2023-01-27 12:57 UTC, merged