모집글 찜 생성 기능 구현
UMC-WithMe/WithMe_Back pull request #83
Opened 2023-02-06 00:23 UTC by dldmldlsy

## 관련 이슈
- Close #81 

## 작업 사항
- MeetLike 엔티티 생성
- MeetLikeDto, MeetLikeCreateRequest 생성
- MeetLikeController 의 createMeetLike 메소드 구현(찜 생성 api)
- MeetLikeService의 createMeetLike 메소드 구현 (db에 찜 추가)
- MeetLikeRepository 생성

## 체크리스트
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2023-02-08 13:32 UTC, hyeonnkang commented on src/main/java/com/umc/withme/dto/like/MeetLikeDto.java
> +}
안에 필드도 없고 코드 상에서 MeetLikeDto 사용하는 곳도 안 보이는 것 같은데 필요 없는 DTO 면 지워도 될 것 같아요!

2023-02-08 15:13 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +     * @param meetId
간단하게라도 parameter에 대한 설명도 적어주시면 좋을 것 같습니다~

2023-02-08 15:13 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +    }
`memberId`에 해당하는 회원이 찜 하려는 모임에 이전에도 찜한 적이 있는지 검증해야 하지 않을까요?

2023-02-10 02:53 UTC, dldmldlsy commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +    }
넵 추가하겠습니다!

2023-02-10 03:21 UTC, dldmldlsy commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +    }
혹시 이미 있는 데이터인지 확인하는 코드가 save안에 포함되어있지않나요?? 추가로 검증하는 작업이 필요한가요?? 자세히는 몰라서,, 알려주시면 감사하겠습니당!

2023-02-10 09:55 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +    }
그게 기존에 저장된 entity인지를 검증하는건데, 방식이 entity 객체의 PK가 null이면 아직 저장되지 않은 entity일거고, PK가 null이 아니라면 이미 저장된 entity이므로 저장하지 않는 로직이 들어가 있어요.
근데 제가 말씀드린 검증은 의미적인 중복 확인 검증이라서 `save`의 로직으로는 검증이 안되고, 저장하기 전에 따로 체크해주셔야 할 것 같습니다.
예를 들어 지금 이 코드라면 동일한 api를 두 번 호출하면 PK는 다르지만 내용 자체는 똑같은 찜이 두개나 만들어져버리니까요!

2023-02-10 09:57 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +        if(meetLikeRepository.findByMember_IdAndMeet_Id(memberId, meetId) ==null){ //해당 찜이 이미 존재하는지 확인
`existByMember_IdAndMeet_Id`로 하시면 존재하는지만 true or false로 확인 가능합니다! 
중복 검증만 하려는거면 성능상 이렇게 하면 좋을 것 같아요!

2023-02-13 04:25 UTC, sujeong11 approved these changes

2023-02-13 04:54 UTC, hyeonnkang approved these changes

2023-02-13 08:14 UTC, Wo-ogie approved these changes

2023-02-13 08:14 UTC, Wo-ogie commented on src/main/java/com/umc/withme/service/MeetLikeService.java
> +             meetLikeRepository.save(meetLike);
이미 찜을 한 모임글인데 또 다시 찜 API가 호출된 경우에는 관련 exception을 throw해서 프론트엔드에도 잘못된 상황이라는 것을 알려주는 것 이 더 좋을 것 같은데 어떨까요?
일단 문제는 없을 것 같아서 approve 할게요!

2023-02-13 08:22 UTC, Wo-ogie requested changes

2023-02-13 08:22 UTC, Wo-ogie commented on src/main/java/com/umc/withme/domain/MeetLike.java
> +        com.umc.withme.domain.MeetLike that = (com.umc.withme.domain.MeetLike) o;
여기서 MeetLike를 package까지 다 명시한 이유가 있을까요?

2023-02-13 12:25 UTC, dldmldlsy commented on src/main/java/com/umc/withme/domain/MeetLike.java
> +        com.umc.withme.domain.MeetLike that = (com.umc.withme.domain.MeetLike) o;
앗 아뇽 지웠습니다!

2023-02-13 18:54 UTC, Wo-ogie approved these changes

2023-02-14 01:26 UTC, merged